<a href="https://colab.research.google.com/github/sumanthgm/Data-Structures-Python/blob/main/Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>2. Write a program to check whether string contains all alphabets (take input from user) using isalpha()</b>
                </font>
            </div>
        </td>
    </tr>
</table>



In [ ]:
string=input('Enter the string')
string.isalpha()


Enter the string PYTGON


False

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>3. Write a program to count number of vowels in a string (take input from user) </b>
                </font>
            </div>
        </td>
    </tr>

In [ ]:
string=input('Enter the String')
Vowels=0

for i in (string):
      if(i=='a' or i=='e' or i=='i' or i=='o' or i=='u' or i=='A' or i=='E' or i=='I' or i=='O' or i=='U'):
        Vowels= Vowels+1

print('Number of vowels are:',Vowels)




Enter the StringSumanth
Number of vowels are: 2


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>4. Write a program to check whether given year is leap year or not (take input from user) </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [ ]:
input_year= int(input('Enter the input year'))
if (input_year%4)==0:
  if (input_year%100)==0:
    if (input_year%400)==0:
      print(str(input_year),+"is not leap year")
    else:
        print(str(input_year),+"is not leap year")
  else:
    print(str(input_year),+"is leap year")
else:
  print( str(input_year)+" is not a leap year")






Enter the input year2025
2025 is not a leap year


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>6. Write a program to print Armstrong number in the interval from 100 to 2000</b>
                </font>
            </div>
        </td>
    </tr>
</table>`


In [ ]:
a=100
b=2000
for n in range (a,b+1):
  order= len(str(n))
  sum=0
  temp=n
  while temp>0:
      degit=temp%10
      sum+=degit**3
      temp//=10
  if sum==n:
    print(n)

# lower_number = 100
# upper_number= 2000
# for num in range(lower_number, upper_number + 1): # upper_number + 1 => because in python indexing strats from 0
#     order = len(str(num)) # order of number
#     sum = 0  # initialize sum
#     temp = num
#     while temp > 0:
#         digit = temp % 10
#         sum += digit ** order
#         temp //= 10
#     if num == sum:
#         print(num)



153
370
371
407


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>7. Write a program to remove punctuations from a string (take a string containing punctuations as an input from user)</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [ ]:
puntuation='''!()-[]{};:'"\,<>./?@#$%^&*_~'''
my_string= input('Eneter the input string')
no_punct=''
for char in (my_string):
  if char not in puntuation:
      no_punct= no_punct+char
print(no_punct)



Eneter the input stringsum<
sum


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>8. Write a program to swap 2 numbers without using temporary variable (take two numbers from user) </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [ ]:
x=int(input('enter the 1 st number:'))
y=int(input('enetr the 2 nd number:'))
x=x+y
y=x-y
x=x-y
print('x:',x,'y:',y)

enter the 1 st number:10
enetr the 2 nd number:20
x: 20 y: 10


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>9. Write a program to print product of two numbers</b>
                    <br><br>
                    <b> a=10 ; b="15"  </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [ ]:
x=int(input('enter the 1 st number:'))
y=int(input('enetr the 2 nd number:'))
product_x=x**2
product_y=y**2
print(product_x,product_y)

enter the 1 st number:10
enetr the 2 nd number:20
100 400


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>13. Write a program to fetch the words from the given list which have their first character in uppercase.</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [ ]:
namesList = ['santa Maria', 'Hello World','Merry christmas', 'tHank You']
solutionList=[]

for name in namesList:
    namevar=name.split()
    for i in range (len(namevar)):
      if namevar[i][0].isupper():
        solutionList.append(namevar[i])

print(solutionList)



['Maria', 'Hello', 'World', 'Merry', 'You']


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>14. A list of dates (dd-mm-yyyy) in the form of string is given below. Create a new list that stores years i.e. the 'yyyy' part from the dates in the given list.</b>
                </font>
            </div>
        </td>
    </tr>
</table>

<b>datesList = ['17-12-1997','22-04-2011','01-05-1993','19-06-2020']</b><br>
<b>Output: ['1997','2011','1993','2020']</b>

In [ ]:
data= ['17-12-1997','22-04-2011','01-05-1993','19-06-2020']
year=[]
for i in data :
  year.append(i.split('-')[2])
print(year)


['1997', '2011', '1993', '2020']


In [ ]:
datesList = ['17-12-1997','22-04-2011','01-05-1993','19-06-2020']
year = []                # An empty list for appending the output
for date in datesList:   # Iterating each element from datesList
    year.append(date.split('-')[2])   # split('-') will split the element in a list w.r.t '-'. Then appending the 3rd element from the splitter list.

print(year)              # Printing the output

['1997', '2011', '1993', '2020']


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>16. Consider the string (quote) given below. Print a string having unique words from the quote (Remove the duplicates from a string and return a new string without duplicates).<br><br> Note: Do not use any string inbuilt function. Also do not use set()</b>
                </font>
            </div>
        </td>
    </tr>
</table>
<b>quote = "God made man man made money money made man mad"</b><br>
<b>Output: God made man money mad</b>

In [ ]:
data="God made man man made money money made man mad"
names=data.split()
newlst=[]

for i in names:
   if i not in newlst:
      newlst.append(i)

print(newlst)

# quote = "God made man man made money money made man mad"
# lst = quote.split()             # split() will split the string on ' ' and put the splitted elements in the list 'lst'.
# newlst = []                     # Creating an empty list
# new_s = " "                     # Creating an empty string to store the output that will not have duplicates

# for word in lst:                # Iterating each word from the splitted list.
#     if word not in newlst:      # Returns True if the word is not present in the empty list 'newlst'.
#         newlst.append(word)     # If the above condition is satisfied, then that wordis appended to the newlst

# new_s = new_s.join(newlst)      # join() joins the list to the string on ' '.
# print(new_s)

['God', 'made', 'man', 'money', 'mad']


God made man money mad


<table align="left">
    <tr>
        <td width="8%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>17. Sort all the elements of the list according to the first letter, irrespective of their cases (uppercase or lowercase)<b>Condition : Do not use any inbuilt sorting function.</b>
                </font>
            </div>
        </td>
    </tr>
</table>


<b>languages = ['python', 'R', 'Java', 'scala', 'C', 'C++']</b><br>
<b>Output: ['C', 'C++', 'Java', 'python', 'R', 'scala']</b>

In [ ]:
languages = ['python', 'R', 'Java', 'scala', 'C', 'C++']
# print(len(languages))

for i in range(len(languages)):      # Iterating through the list
    for j in range(i+1, len(languages)):      # Iterating through the same list but with indices i+1
        if(languages[i][0].lower() > languages[j][0].lower()):    # Comparing the first characters of the words at index i and i+1.
            languages[i], languages[j] = languages[j], languages[i]     # Swapping the words position if the above condition is met.

print(languages)

['C', 'C++', 'Java', 'python', 'R', 'scala']


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b> 21. A list of Power Levels of superheroes is given. Also, the Category is provided according to the range for information. Group the heroes(in list) as per their corresponding category according to the power levels.</b><br>
                    <br>
                    <b> Sample Output: God_like = ['Thor', 'Thanos']</b>
                </font>
            </div>
        </td>
    </tr>
</table>

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>1. Write a program to print following pattern</b>
                    <br>
                 </font>
            </div>
        </td>
    </tr>
</table>

In [ ]:
number=6
Asci_number=65
for i in range (number):
  for j in range (i+1):
      asci= chr(Asci_number)
      print(asci,end=" ")
      Asci_number+=1
  print()


A 
B C 
D E F 
G H I J 
K L M N O 
P Q R S T U 


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>2. Write a program to print tables from 2 to a user provided range (take number from user)
                 </font>
            </div>
        </td>
    </tr>
</table>

In [ ]:
# In= int(input('Enetr the customer range input'))

# for i in range (2,In):

# range_num = int(input('Enter a number in range: '))

# for n in range(2 , range_num + 1):
#     for i in range(1,11):
#         print(n, ' X ', i, ' = ', n*i)
#     print("\n")

range_num = int(input('Enter a number in range: '))
for i in range (2, range_num+1):
  for j in range (1,11):
    print(i,'X',j,"=",i*j)
  print("\n")

Enter a number in range: 5
2 X 1 = 2
2 X 2 = 4
2 X 3 = 6
2 X 4 = 8
2 X 5 = 10
2 X 6 = 12
2 X 7 = 14
2 X 8 = 16
2 X 9 = 18
2 X 10 = 20


3 X 1 = 3
3 X 2 = 6
3 X 3 = 9
3 X 4 = 12
3 X 5 = 15
3 X 6 = 18
3 X 7 = 21
3 X 8 = 24
3 X 9 = 27
3 X 10 = 30


4 X 1 = 4
4 X 2 = 8
4 X 3 = 12
4 X 4 = 16
4 X 5 = 20
4 X 6 = 24
4 X 7 = 28
4 X 8 = 32
4 X 9 = 36
4 X 10 = 40


5 X 1 = 5
5 X 2 = 10
5 X 3 = 15
5 X 4 = 20
5 X 5 = 25
5 X 6 = 30
5 X 7 = 35
5 X 8 = 40
5 X 9 = 45
5 X 10 = 50




13. Create a dictionary containing four lambda functions square, cube, squareroot, multiply by 2.

E.g. dict = {'Square': function for squaring, 'Cube': function for cube, 'Squareroot': function for squareroot, 'Double': function for double} and so on

Pass the values (input from the user) to the functions in the dictionary respectively. Then add the outputs of each function and print it.

In [ ]:
# Take input from user for each function parameter inside the dictionary
inpsq = int(input('Enter first number: '))
inpcu = int(input('Enter second number: '))
inproot = int(input('Enter third number: '))
inpdouble = int(input('Enter forth number: '))


diclamda={'square':lambda x:x**2,'Cube':lambda x:x**3,'Root':lambda x:(x**0.5),'Double':lambda x:x*2}
print (diclamda['square'](inpsq))
result=diclamda['square'](inpsq)+diclamda['Cube'](inpcu)+diclamda['Root'](inproot)+diclamda['Double'](inpdouble)

print(result)

Enter first number: 2
Enter second number: 2
Enter third number: 2
Enter forth number: 2
4
17.414213562373096


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>14. A list of words is given. Find the words from the list that have their second character in uppercase.</b>
                </font>
            </div>
        </td>
    </tr>
</table>

<b>ls = ['hello', 'Dear', 'hOw', 'ARe', 'You']</b><br>
<b>Output: ['hOw', 'ARe']</b>

In [ ]:
words=['hello', 'Dear', 'hOw', 'ARe', 'You']

def functionNames(x):
    if x[1].isupper():
        return True
    else:
        False

list (filter(functionNames,words))


# words = ['hello', 'Dear', 'hOw', 'ARe', 'You']

# def filterNames(x):                 # Creating a function filterNames(parameter) that will return the result as a boolean value
#     if x[1].isupper():              # Checking whether the second character of the word fromthe list 'ls' is in upper case or not.
#         return True
#     else:
#         return False
# list(filter(filterNames, words))


['hOw', 'ARe']

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>15. Filter the marks from the tuple "tmarks" that are  greater than 40 and print corresponding names from the "tnames" tuple.</b><br><br>
                </font>
            </div>
        </td>
    </tr>
</table>

<b>tnames = ('John','Sharon','Jack','Annie')</b><br>
<b>tmarks = (32,50,75,12)</b>

In [ ]:
tnames = ('John','Sharon','Jack','Annie')
tmarks = (32,50,75,12)

def sorttmark(x):
  if x>40:
    return True
  else:
    return False
marks= list(filter(sorttmark,tmarks))
for j in marks:
  print(tnames[tmarks.index(j)])

# tnames = ('John','Sharon','Jack','Annie')     # Tuple with names of the students
# tmarks = (32,50,75,12)                        # Tuplw with marks of the respective students from 'tnames'

# def filterMarks(x):                           # Creating a function to check if the marks are above 40. Returns Boolean value.
#     if x > 40:                                # Check if marks are greater than 40. If yes,
#         return True                           # Return True
#     else:                                     # Else return False
#         return False

# marks = list(filter(filterMarks, tmarks))     # A list of marks that are greater than 40 is stored in marks variable

# for j in marks:                               # Iterating through the marks list
#     print(tnames[tmarks.index(j)])



Sharon
Jack


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>1. Create an array of integers from 20 to 2 with a step of -2
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [5]:
import numpy as np
array= np.arange(20,2,-2)
array

array([20, 18, 16, 14, 12, 10,  8,  6,  4])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>2. Find the minimum value along with the row
</b>
                </font>
            </div>
        </td>
    </tr>
</table>


#### Create a 2D Numpy array from list of lists
arr2D = np.array([[110, 102, 183],
                     [140, 175, 106],
                     [170, 195, 117],
                     [192, 140, 195]])

In [12]:
arr2D=np.array([[110, 102, 183],
                [140, 175, 106],
                [170, 195, 117],
                [192, 140, 195]])
finmin=np.amin(arr2D,axis=1)
finmin

array([102, 106, 117, 140])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>3. Replace all odd numbers in array with -2
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below**<br>
arr = np.array([0, 31, 42, 43, 34, 45, 26, 27, 38, 94, 65, 78, 76])

In [13]:
arr=np.array([0,31,42,43,34,45,26,27,38,94,65,78,76])
out=np.where(arr%2==1,-2,arr)
out

array([ 0, -2, 42, -2, 34, -2, 26, -2, 38, 94, -2, 78, 76])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>5. Stack two arrays vertically
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>
array1 = np.arange(10).reshape(2,-1)<br>
array2 = np.repeat(1, 10).reshape(2,-1)

In [33]:
array1 = np.arange(10).reshape(2,-1)
print(array1)
array2 = np.repeat(1, 10).reshape(2,-1)
print(array2)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [45]:
# concate
concat=np.concatenate([array1,array2],axis=0)

print(concat)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [49]:
np.vstack(concat)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Remove the array one values if have same array two

In [58]:
arr1=np.array([1,2,3,5,6])
arr2=np.array([5,6,7,8,9])
rov_diff=np.setdiff1d(arr1,arr2)
print(rov_diff)

[1 2 3]


<!-- Remove same in both arraya
 -->